import { Navbar } from '@/components/Navbar'

export function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="mx-auto max-w-4xl px-6 py-32">
        <h1 className="mb-8 text-4xl font-bold text-text">Terms of Service</h1>
        <div className="prose prose-invert max-w-none text-text-muted space-y-6">
          <p className="text-sm text-text-dim">Last updated: {new Date().toLocaleDateString()}</p>
          
          <section>
            <h2 className="text-2xl font-semibold text-text mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using FoundryForge, you agree to be bound by these Terms of Service and all applicable laws and regulations.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold text-text mb-3">2. Description of Service</h2>
            <p>FoundryForge provides AI-powered software architecture planning and code generation tools. The outputs are generated by artificial intelligence and should be reviewed by competent developers before use in production.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold text-text mb-3">3. User Responsibilities</h2>
            <p>You are responsible for the prompts you submit and the resulting outputs you choose to use. You agree not to use the service for any unlawful purposes or to generate malicious code.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold text-text mb-3">4. Intellectual Property</h2>
            <p>You retain ownership of any intellectual property rights that you hold in the prompts you submit. The generated architectures and code are provided for your use subject to our licensing terms.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
